# This is a workflow to build the docker image and deploy it
name: Deploy Backend Application

on: 
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin    
      - name: Build Docker Image
        run: docker build -t tlhalefosebaeng/simple-crud-app-backend ./backend
      - name: Publish Image to docker hub
        run: docker push tlhalefosebaeng/simple-crud-app-backend:latest 
 
  deploy:
    needs: build
    runs-on: [self-hosted, backend-runner]
    steps:
        - name: Create Docker network (if not exists)
          run: docker network create simple-crud-app-network || true
        - name: Pull image from docker hub
          run: docker pull tlhalefosebaeng/simple-crud-app-backend:latest 
        - name: Delete old container
          run: docker rm -f backend-container
        - name: Run Docker Container
          run: |
            docker run -d -p 3000:3000 --name backend-container \
            --network simple-crud-app-network \
            -e PORT="${{ secrets.BACKEND_PORT }}" \
            -e DATABASE_URI="${{ secrets.DATABASE_URI }}" \
            -e FRONTEND_BASE_URL="${{ secrets.FRONTEND_BASE_URL }}" \
            tlhalefosebaeng/simple-crud-app-backend
