# This is a workflow to build the frontend docker image and deploy it
name: Deploy Frontend Application

on: 
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source
              uses: actions/checkout@v4
            - name: Login to docker hub
              run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            - name: Build Docker Image
              run: docker build -t tlhalefosebaeng/simple-crud-app-frontend --build-arg BACKEND_BASE_URL='${{ secrets.BACKEND_BASE_URL }}' ./frontend
            - name: Publish Image to docker hub
              run: docker push tlhalefosebaeng/simple-crud-app-frontend:latest 
    deploy:
        needs: build
        runs-on: [self-hosted, frontend-runner]
        steps:
            - name: Pull image from docker hub
              run: docker pull tlhalefosebaeng/simple-crud-app-frontend:latest 
            - name: Delete old container
              run: docker rm -f frontend-container
            - name: Run Docker Container
              run: |
                docker run -d -p 80:80 --name frontend-container \
                tlhalefosebaeng/simple-crud-app-frontend